/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PriceRouteImport } from './routes/price'
import { Route as RecallRouteImport } from './routes/recall'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StockRouteImport } from './routes/stock'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as ScheduleApptIdRouteImport } from './routes/schedule.$apptId'
import { Route as ScheduleNewRouteImport } from './routes/schedule.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRoute = PriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallRoute = RecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleApptIdRoute = ScheduleApptIdRouteImport.update({
  id: '/$apptId',
  path: '/$apptId',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleNewRoute = ScheduleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScheduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discounts': typeof DiscountsRoute
  '/finance': typeof FinanceRoute
  '/patients': typeof PatientsRouteWithChildren
  '/photos': typeof PhotosRoute
  '/plans': typeof PlansRoute
  '/price': typeof PriceRoute
  '/recall': typeof RecallRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/patients/$id': typeof PatientsIdRoute
  '/schedule/$apptId': typeof ScheduleApptIdRoute
  '/schedule/new': typeof ScheduleNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discounts': typeof DiscountsRoute
  '/finance': typeof FinanceRoute
  '/photos': typeof PhotosRoute
  '/plans': typeof PlansRoute
  '/price': typeof PriceRoute
  '/recall': typeof RecallRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/patients/$id': typeof PatientsIdRoute
  '/schedule/$apptId': typeof ScheduleApptIdRoute
  '/schedule/new': typeof ScheduleNewRoute
  '/patients': typeof PatientsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discounts': typeof DiscountsRoute
  '/finance': typeof FinanceRoute
  '/patients': typeof PatientsRouteWithChildren
  '/photos': typeof PhotosRoute
  '/plans': typeof PlansRoute
  '/price': typeof PriceRoute
  '/recall': typeof RecallRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/patients/$id': typeof PatientsIdRoute
  '/schedule/$apptId': typeof ScheduleApptIdRoute
  '/schedule/new': typeof ScheduleNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/discounts'
    | '/finance'
    | '/patients'
    | '/photos'
    | '/plans'
    | '/price'
    | '/recall'
    | '/schedule'
    | '/settings'
    | '/stats'
    | '/stock'
    | '/patients/$id'
    | '/schedule/$apptId'
    | '/schedule/new'
    | '/patients/'
    | '/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/discounts'
    | '/finance'
    | '/photos'
    | '/plans'
    | '/price'
    | '/recall'
    | '/settings'
    | '/stats'
    | '/stock'
    | '/patients/$id'
    | '/schedule/$apptId'
    | '/schedule/new'
    | '/patients'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/discounts'
    | '/finance'
    | '/patients'
    | '/photos'
    | '/plans'
    | '/price'
    | '/recall'
    | '/schedule'
    | '/settings'
    | '/stats'
    | '/stock'
    | '/patients/$id'
    | '/schedule/$apptId'
    | '/schedule/new'
    | '/patients/'
    | '/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  DiscountsRoute: typeof DiscountsRoute
  FinanceRoute: typeof FinanceRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PhotosRoute: typeof PhotosRoute
  PlansRoute: typeof PlansRoute
  PriceRoute: typeof PriceRoute
  RecallRoute: typeof RecallRoute
  ScheduleRoute: typeof ScheduleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price': {
      id: '/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof PriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recall': {
      id: '/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof RecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/$apptId': {
      id: '/schedule/$apptId'
      path: '/$apptId'
      fullPath: '/schedule/$apptId'
      preLoaderRoute: typeof ScheduleApptIdRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/new': {
      id: '/schedule/new'
      path: '/new'
      fullPath: '/schedule/new'
      preLoaderRoute: typeof ScheduleNewRouteImport
      parentRoute: typeof ScheduleRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface ScheduleRouteChildren {
  ScheduleApptIdRoute: typeof ScheduleApptIdRoute
  ScheduleNewRoute: typeof ScheduleNewRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
}

const ScheduleRouteChildren: ScheduleRouteChildren = {
  ScheduleApptIdRoute: ScheduleApptIdRoute,
  ScheduleNewRoute: ScheduleNewRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
}

const ScheduleRouteWithChildren = ScheduleRoute._addFileChildren(
  ScheduleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  DiscountsRoute: DiscountsRoute,
  FinanceRoute: FinanceRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PhotosRoute: PhotosRoute,
  PlansRoute: PlansRoute,
  PriceRoute: PriceRoute,
  RecallRoute: RecallRoute,
  ScheduleRoute: ScheduleRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
